name: nowplaying
description: A plugin to reveal metadata for the currently playing audio track
repository: https://github.com/shinyford/nowplaying
version: 3.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.1
  package_info_plus: ^8.0.0
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.1.1
  spotify: ^0.13.3
  uuid: ^4.2.2
  webview_flutter: ^4.7.0

dev_dependencies:
  platform: ^3.1.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  plugin:
    platforms:
      android:
        package: com.gomes.nowplaying
        pluginClass: NowPlayingPlugin
      ios:
        pluginClass: NowPlayingPlugin

  assets:
    - assets/
